/:
  controller: main
  action: home

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/forget:
  controller: user
  action: pwdforget


/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin
    - user