/:
    controller: main
    action: home

/contact:
    controller: main
    action: contact

/logout:
    controller: user
    action: logout
    security:
        - user
        - admin

/register-login:
    controller: user
    action: register_login

/mail-validation:
  controller: user
  action: mailValidation

/certification-request:
  controller: certification
  action: certificationRequest

/get-certifications:
  controller: certification
  action: getCertifications

/get-certification:
  controller: certification
  action: getCertificationById

/modify-certification-status:
  controller: certification
  action: modifyCertificationStatus

/forget:
    controller: user
    action: pwdforget

/recette:
    controller: article
    action: getArticle

/create-recette:
    controller: article
    action: create
    security:
    - user
    - chief

/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin
    - user

/list:
  controller: admin
  action: list
  security:


/get-user:
  controller: user
  action: getUserById
  security:


/get-users:
  controller: user
  action: getUsers

/delete-user:
  controller: user
  action: deleteUserById
  security:
  
/article-creation:
    controller: article
    action: create
    security:
        - user

/ingredient-request:
  controller: ingredient
  action: ingredientRequest

/get-ingredients:
  controller: ingredient
  action: getIngredients

/get-ingredient:
  controller: ingredient
  action: getIngredientById

/modify-ingredient-status:
  controller: ingredient
  action: modifyIngredientStatus
  
/theme:
    controller: theme
    action: handleTheme

/list-themes:
    controller: theme
    action: listThemes

/delete-theme:
    controller: theme
    action: deleteThemeById

/settings:
  controller: admin
  action: settings

