/:
    controller: main
    action: home

/contact:
    controller: main
    action: contact

/login:
    controller: user
    action: login

/logout:
    controller: user
    action: logout
    security:
        - user
        - admin

/register:
    controller: user
    action: register

/forget:
    controller: user
    action: pwdforget

/handle-article:
    controller: article
    action: handleArticle

/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin
    - user

/list:
  controller: admin
  action: list
  security:


/get-user:
  controller: user
  action: getUserById
  security:


/get-users:
  controller: user
  action: getUsers
  security:
