routes:
    '/':
        controller: index
        action: index
        method: get
    '/{id}':
        controller: index
        action: show
        method: get

    '/{user}':
        controller: index
        action: show
        method: get
