/:
    controller: main
    action: home
/recettes:
    controller: main
    action: searchArticles

/cuisiniers:
    controller: main
    action: searchChiefs


/logout:
    controller: user
    action: logout
    security:
        - user
        - chief
        - admin

/register-login:
    controller: user
    action: register_login

/mail-validation:
  controller: user
  action: mailValidation

/certification-request:
  controller: certification
  action: certificationRequest
  security:
      - user

/get-certifications:
  controller: certification
  action: getCertifications
  security:
      - admin

/get-certification:
  controller: certification
  action: getCertificationById
  security:
      - admin

/modify-certification-status:
  controller: certification
  action: modifyCertificationStatus
  security:
      - admin

/forget:
    controller: user
    action: pwdforget

/recette:
    controller: article
    action: getArticle

/recette/edit:
    controller: article
    action: editArticle
    security:
      - chief

/set-score:
    controller: article
    action: setArticleScore
    security:
      - user
      - chief
      - admin


/create-recette:
    controller: article
    action: create
    security:
    - user
    - chief

/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin

/list:
  controller: admin
  action: list
  security:
    - admin

/categories:
  controller: category
  action: categories
  security:
    - admin

/delete-category:
  controller: category
  action: deleteCategoryById
  security:
    - admin


/get-user:
  controller: user
  action: getUserById
  security:
    - admin


/get-users:
  controller: user
  action: getUsers
  security:
    - admin

/delete-user:
  controller: user
  action: deleteUserById
  security:
    - admin

/active-user:
  controller: user
  action: updateActiveUser
  security:
    - admin

/status-user:
  controller: user
  action: updateStatusUser
  security:
    - admin

  
/article-creation:
    controller: article
    action: create
    security:
      - chief
      - admin

/get-articles:
  controller: article
  action: getArticles
  security:
    - admin

/get-article:
  controller: article
  action: getArticleById
  security:
    - admin

/ingredient-request:
  controller: ingredient
  action: ingredientRequest
  security:
      - chief
      - admin

/get-ingredients:
  controller: ingredient
  action: getIngredients
  security:
    - admin

/get-ingredient:
  controller: ingredient
  action: getIngredientById
  security:
    - admin

/modify-ingredient-status:
  controller: ingredient
  action: modifyIngredientStatus
  security:
    - admin
  
/theme:
    controller: theme
    action: handleTheme
    security:
      - admin

/list-themes:
    controller: theme
    action: listThemes
    security:
      - admin

/delete-theme:
    controller: theme
    action: deleteThemeById
    security:
      - admin

/settings:
  controller: admin
  action: settings
  security:
    - admin

/create-comment:
  controller: comment
  action: createComment
  security:
      - user
  
/profile:
  controller: user
  action: profile

/get-comments:
  controller: comment
  action: getComments
  security:
    - admin

/get-comment:
  controller: comment
  action: getCommentById
  security:
    - admin

/modify-comment-status:
  controller: comment
  action: modifyCommentStatus
  security:
    - admin

/modify-profile-picture:
  controller: user
  action: modifyProfilePicture
  security:
      - user
      - chief
      - admin

/404:
  controller: main
  action: notFound
  
/create-page:
  controller: page
  action: createPage
  security:
    - admin

/get-pages:
  controller: page
  action: getPages
  security:
    - admin

/get-page:
  controller: page
  action: getPageById
  security:
    - admin

/delete-page:
  controller: page
  action: deletePageById
  security:
    - admin

/page/edit:
  controller: page
  action: editPage
  security:
    - admin
  
/setup:
  controller: admin
  action: setup


/pwd-forget:
  controller: user
  action: pwdforget

/modify-password:
  controller: user
  action: modifyPassword