routes:
    '/':
        controller: Index
        action: render
        method: get

    '/login':
        controller: Page
        action: render
        method: post

    '/404':
        controller: Page
        action: render
        method: post
