/:
    controller: main
    action: home

/contact:
    controller: main
    action: contact

/login:
    controller: user
    action: login

/logout:
    controller: user
    action: logout

/register:
    controller: user
    action: register

/forget:
    controller: user
    action: pwdforget

<<<<<<< HEAD
/handle-article:
  controller: article
  action: handleArticle

=======
/article-creation:
    controller: article
    action: create
    security:
        - user
>>>>>>> enh(editorjs): add editorjs partial

/dashboard:
    controller: admin
    action: dashboard
    security:
        - admin
        - user
