routes:
    '/':
        controller: Index
        action: render

    '/login':
        controller: UserController
        action: login

    '/logout':
        controller: UserController
        action: logout

    '/404':
        controller: Error
        action: error404
